- name: Instalar y configurar MariaDB
  hosts: db
  become: true
  tasks:
    - name: Instalar MariaDB y dependencias python
      apt:
        name:
          - mariadb-server
          - python3-pymysql
        update_cache: true

    - name: Asegurar que MariaDB arranca
      service:
        name: mariadb
        state: started
        enabled: true

    - name: Permitir escucha en todas las interfaces (0.0.0.0)
      lineinfile:
        path: /etc/mysql/mariadb.conf.d/50-server.cnf
        regexp: '^bind-address'
        line: 'bind-address = 0.0.0.0'

    - name: Reiniciar MariaDB
      service:
        name: mariadb
        state: restarted

    - name: Crear base de datos WordPress
      community.mysql.mysql_db:
        name: "{{ wp_db_name }}"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock

    - name: Crear usuario WordPress y permisos
      community.mysql.mysql_user:
        name: "{{ wp_db_user }}"
        password: "{{ wp_db_pass }}"
        priv: "{{ wp_db_name }}.*:ALL"
        host: "%"
        state: present
        login_unix_socket: /var/run/mysqld/mysqld.sock